### ISSUE TITLE
Add compatibility with Pillow 4.0

### ISSUE THREAD

**Issue by dirkmueller** [kallimachos/sphinxmark#23]
Currently sphinxmark has install_requires on Pillow < 3.5, although meanwhile 4.0 released. I have not investigated what changed but it would be nice to have this coinstallable with Pillow 4.0

**Comment by kallimachos** [comment]
Pillow 4.0 looks like it should work fine. I'll update the requirements.

**Comment by kallimachos** [comment]
Included in Sphinxmark 0.1.17 release.
